version: 0.1

environment_variables:
  plaintext:
    SLACK_HEADER: 'content-type: application/json'
    PAYLOAD: '{"username": "CodeBuild", "text": "Build Start"}'
#    PAYLOAD_END: '{"username": "CodeBuild", "text": "'${FIN}'"}'
#     key: "value"
#     JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
            
phases:
  install:
    commands:
      - echo "curl -X POST --data-urlencode payload='$PAYLOAD' $SLACK_URL"
      - curl -X POST --data-urlencode payload="'"$PAYLOAD"'" $SLACK_URL
#      - npm install -g gitbook-cli
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
#      - gitbook install
  build:
    commands:
      - gitbook build
  post_build:
    commands:
      - echo Build completed on `date`
      - FIN=Build completed on `date`
      - ls -la
#      - curl -X POST --data-urlencode payload="'"PAYLOAD_END"'" $SLACK_URL
artifacts:
#  type: zip
  files:
    - _book/*
#     - location
#     - target/messageUtil-1.0.jar
#   discard-paths: yes
#   base-directory: _book
  
