version: 0.1

environment_variables:
  plaintext:
    key: "value"
    key: "value"
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
            
phases:
  install:
    commands:
      - npm install -g gitbook-cli
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - gitbook install
  build:
    commands:
      - gitbook build
  post_build:
    commands:
      - echo Build completed on `date`
# artifacts:
#   files:
#     - location
#     - location
#     - target/messageUtil-1.0.jar
#   discard-paths: yes
#   base-directory: location
  
