version: 0.1

environment_variables:
  plaintext:
    SLACK_HEADER: 'content-type: application/json'
    SLACK_DATA: '{"username": "CodeBuild", "text": "Build Start"}'
    SLACK_SUCCESS: '{"username": "CodeBuild", "text": "Build Success"}'
    PAYLOAD: 'payload={"username": "CodeBuild", "text": "Build Start"}'
#     key: "value"
#     JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
            
phases:
  install:
    commands:
      - curl -X POST --data-urlencode $PAYLOAD $SLACK_URL -H $SLACK_HEADER
      - npm install -g gitbook-cli
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - gitbook install
  build:
    commands:
      - gitbook build
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -la
      - curl -X POST --data-urlencode $PAYLOAD $SLACK_URL -H $SLACK_HEADER
artifacts:
#  type: zip
  files:
    - _book/*
#     - location
#     - target/messageUtil-1.0.jar
#   discard-paths: yes
#   base-directory: _book
  
