version: 0.1

# environment_variables:
#   plaintext:
#     key: "value"
#     key: "value"
#     JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
            
phases:
  install:
    commands:
      - curl -X POST $SLACK_URL -H 'content-type: application/json' -d '{"username": "CodeBuild", "text": "Build Start"}'
      - npm install -g gitbook-cli
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - gitbook install
  build:
    commands:
      - gitbook build
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -la
      - curl -X POST $SLACK_URL -H 'content-type: application/json' -d '{"username": "CodeBuild", "text": "Build Success"}'
artifacts:
#  type: zip
  files:
    - _book/*
#     - location
#     - target/messageUtil-1.0.jar
#   discard-paths: yes
#   base-directory: _book
  
